import { SITE, BLOG, GITHUB, LINKEDIN } from './theme'
import type { Block, Row } from './page'
import type { Data } from './data'

const esc = (s: string) => s.replace(/&/g, '&amp;').replace(/"/g, '&quot;').replace(/</g, '&lt;')

/**
 * GitHub picks the <source> that matches the viewer's colour mode, so each
 * block ships as a light and a dark SVG. The <img> carries the width/alt.
 */
const picture = (b: Block) =>
  `<picture><source media="(prefers-color-scheme: dark)" srcset="./assets/dark/${b.file}"><img src="./assets/light/${b.file}" width="${b.width}" align="top" alt="${esc(b.alt)}"></picture>`

const block = (b: Block) => (b.href ? `<a href="${b.href}">${picture(b)}</a>` : picture(b))

/** Two cards on one line are separated by a single space — the only gap GitHub allows. */
const row = (r: Row) => r.map(block).join(' ')

export function readme(data: Data, rows: Row[]): string {
  return `<!--
  Generated by scripts/build.tsx — do not edit by hand.
  Every block below is a React component rendered to a self-contained,
  animated SVG (fonts inlined, SMIL animations, no JavaScript), once for
  GitHub's light theme and once for dark. Edit src/ and run \`bun run all\`.
-->
<div align="center">

${rows.map(row).join('\n')}

</div>

<p align="center">
  <a href="${SITE}">zhy0216.github.io</a> &nbsp;·&nbsp;
  <a href="${BLOG}">Field notes</a> &nbsp;·&nbsp;
  <a href="${LINKEDIN}">LinkedIn</a> &nbsp;·&nbsp;
  <a href="${GITHUB}?tab=repositories">All repositories</a>
</p>

<details>
<summary>How this page is built</summary>

Every block above is a React component rendered to a static, self-contained SVG: fonts are inlined, motion is SMIL, and there is no JavaScript, so it animates inside GitHub's \`<img>\` sandbox. Each block is rendered twice and served through \`<picture>\`, so it follows your GitHub colour mode.

\`\`\`sh
bun install
bun run fetch    # GitHub GraphQL → data/github.json (GITHUB_TOKEN or a logged-in gh CLI)
bun run build    # src/ → assets/{light,dark}/*.svg + this README
bun run preview  # preview/light.html + preview/dark.html, as GitHub renders them
\`\`\`

A GitHub Action re-runs the pipeline every day so the calendar, the counters and the notes stay current. Snapshot: ${data.fetchedAt.slice(0, 10)}.

</details>
`
}
